[MVP] Backend con Cola de Consultas
algoritmos-iii/algo3_backend pull request #2
Opened 2022-08-21 19:26 UTC by ilitteri

## Antes de mergear

Este PR depende de #1. ✅ 

### TODOs

- [x] README.md
- [ ] CONTRIBUTING.md (podemos dejarlo para el futuro).
- [x] Makefile
- [ ] Dockerfile
- [x] Circle CI
- [ ] Codecov (por el momento está bugueado).

## Motivación

Este backend va a servir de plataforma para todas las apps que tengamos en la cátedra. La idea de este MVP es tener lo mínimo indispensable que necesita el frontend del bot de discord en cuanto a la funcionalidad de la cola de consultas y además servir de estructura del backend como para que a partir de acá sea trivial el hecho de agregar los endpoints que hagan falta así como las estructuras necesarias para lograr la funcionalidad de dichos endpoints.

## Endpoints
*En el futuro se agregará la documentación pertinente en el README*

`GET /api/discord/v1/next` - Obtiene el siguiente grupo a atender.
`POST /api/discord/v1/dismiss_help` - Pedido de desestimación de consulta de grupo.
`POST /api/discord/v1/enqueue_help` - Pedido de consulta de grupo.
`PATCH /api/discord/v1/clear_help_queue` - Limpia la cola de consultas.
`GET /api/discord/v1/help_queue` - Devuelve la cola de consultas en orden.

## Prerrequisitos 

Debes tener Rust instalado. Para instalarlo ejecutá los siguientes comandos.

```bash
curl https://sh.rustup.rs -sSf | sh -s -- -y

source "$HOME/.cargo/env"
```

## Build and Run

Ejecutar el siguiente comando compilará y ejecutará el binario que estará escuchando requests en el puerto `8080` en `localhost` por default.

```bash
make run
```

La directiva de arriba admite las siguientes opciones:
- `DOMAIN`: el dominio en el que se alojará el backend. Es `http://127.0.0.1` por defecto (en un futuro `https`).
- `PORT`: el puerto en el que el backend escuchará requests. Es `8080` por defecto.

## Para probar

El `Makefile` dispone de las siguientes directivas para jugar un poco con la API:

```bash
make test_enqueue_help
make test_get_next
make test_dismiss 
make test_clear
make test_get_queue
```

Todas las directivas de arriba tienen como opciones opcionales `DOMAIN` y `PORT` exceptuando a las siguientes:

- `test_enqueue_help` admite opcionalmente la opción `GROUP` para indicar el grupo que pide ayuda. Por defecto es `0`.
- `test_get_next` admite opcionalmente la opción `HELPER` para indicar el ayudante que brinda la ayuda. Por defecto es `Ayudante`.
- `test_dismiss_help` admite opcionalmente la opción `GROUP` para indicar el grupo que desestima la ayuda. Por defecto es `0`.

## Para correr los tests

Para correr la suite de tests corré el siguiente comando en consola:

```bash
make test
```

2022-08-23 15:46 UTC, julitaras commented
> En el futuro se agregará la documentación pertinente en el README
Deberiamos agregarla en un swagger, haciendo una carpeta de `docs/specs` y que ahi este el `swagger.yaml`. Obvio en el readme lo linkeamos! Incluso eso podria estar en el githubpages :)

2022-08-23 15:52 UTC, julitaras requested changes

2022-08-23 15:52 UTC, julitaras commented on README.md
> +
Hay que tener algo instalado? De ser asi, donde se consigue?

2022-08-23 15:52 UTC, julitaras commented on src/help_queue.rs
> +type Group = u16;
No pesaba que aqui ibamos a manejar la cola del bot sino mas bien que iba a contener apis generales de la cual requerimos informacion. Ejemplo: Lista de alumnos, Lista de grupos, etc etc

2022-08-23 15:52 UTC, julitaras commented
Reitero que me genera cierta duda esto de que amos a poner cosas de la cola, realmente pense que tenia otro fin. Por fa si podemos juntarnos para rever esto

2022-08-23 19:16 UTC, ilitteri commented
> 

Efectivamente este backend va a servir de plataforma para todas las apps que tengamos en la cátedra. La idea de este MVP era tener una estructura del backend como para que a partir de acá sea trivial el hecho de agregar los endpoints que hagan falta así como las estructuras necesarias para lograr la funcionalidad de dichos endpoints.

2022-08-23 19:25 UTC, ilitteri commented on src/help_queue.rs
> +type Group = u16;
Es verdad que dejé el nombre mal de la estructura principal y lleva a confuciones. Le cambio el nombre para que se entienda mejor.

2022-08-23 19:34 UTC, julitaras commented
> > Reitero que me genera cierta duda esto de que amos a poner cosas de la cola, realmente pense que tenia otro fin. Por fa si podemos juntarnos para rever esto
> 
> Efectivamente este backend va a servir de plataforma para todas las apps que tengamos en la cátedra. La idea de este MVP era tener una estructura del backend como para que a partir de acá sea trivial el hecho de agregar los endpoints que hagan falta así como las estructuras necesarias para lograr la funcionalidad de dichos endpoints.
> 
> Igual es cierto como dije en el comentario de arriba que la estructura principal quedó con el nombre `HelpQueue` cuando se trata de la estructura que levanta el server y contiene las estructuras auxiliares que lleguen a necesitar los distintos endpoints.
> 
> Me parece bien igual organizar una reunión para aclarar esto por si no me expliqué bien.

Genial Ivo, gracias por la aclaracion!

2022-08-23 23:09 UTC, ilitteri commented on README.md
> +
Sip, ya lo agrego.

2022-08-23 23:13 UTC, ilitteri commented
@julitaras ahí refactoricé el código para que sea extensible para las demás necesidades de la cátedra. Si te parece organizamos una reunión para hablar sobre el código y cómo extenderlo.

2022-08-23 23:16 UTC, ilitteri commented
> > > Reitero que me genera cierta duda esto de que amos a poner cosas de la cola, realmente pense que tenia otro fin. Por fa si podemos juntarnos para rever esto
> > 
> > 
> > Efectivamente este backend va a servir de plataforma para todas las apps que tengamos en la cátedra. La idea de este MVP era tener una estructura del backend como para que a partir de acá sea trivial el hecho de agregar los endpoints que hagan falta así como las estructuras necesarias para lograr la funcionalidad de dichos endpoints.
> > Igual es cierto como dije en el comentario de arriba que la estructura principal quedó con el nombre `HelpQueue` cuando se trata de la estructura que levanta el server y contiene las estructuras auxiliares que lleguen a necesitar los distintos endpoints.
> > Me parece bien igual organizar una reunión para aclarar esto por si no me expliqué bien.
> 
> Genial Ivo, gracias por la aclaracion!

No por nada! Me gustaría que usemos este PR para hablar de estas cosas y aclarar todo lo que sea necesario para poder seguir adelante ya que esto vendría siendo el scafolding.

Invito a @ManuSanchez02 y @mrti259 a chusmear y a hacer preguntas ( al resto no lo etiqueto porque ya conocen Rust pero igual vengan a chusmear @josuebouchard @IAvecilla ).

2022-08-23 23:57 UTC, julitaras commented on src/help_queue.rs
> +/// The help queue.
Me gustaria que en algun lado quede claro que esto es una especie de dummy para poder guiarnos para el resto de los endpoints

2022-08-24 00:48 UTC, ilitteri commented on src/help_queue.rs
> +/// The help queue.
No es dummy, es un MVP del backend que solo tiene el código de la cola de consultas para el bot.

2022-08-24 00:50 UTC, ilitteri commented on src/help_queue.rs
> +/// The help queue.
Es lo que es pero además sirve como base para el resto.

2022-08-24 13:05 UTC, julitaras commented on src/help_queue.rs
> +/// The help queue.
Pero entonces es para que sirva de base o es parte del backend jajajaj

2022-08-24 14:01 UTC, ilitteri commented on src/help_queue.rs
> +/// The help queue.
Ambos

2022-09-05 13:36 UTC, julitaras approved these changes
Apruebo para no bloquear el resto de los flujos, pero insisto en que no me queda claro que este endpoint deba estar aca. Me la sensacion que deberia estar en el bot. Sino esto se va a convertir en una especie de bolsa de gatos jajajaj

2022-09-05 14:15 UTC, ilitteri commented
> Apruebo para no bloquear el resto de los flujos, pero insisto en que no me queda claro que este endpoint deba estar aca. Me la sensacion que deberia estar en el bot. Sino esto se va a convertir en una especie de bolsa de gatos jajajaj

A cuál endpoint te referís en específico?

2022-09-05 14:22 UTC, julitaras commented
> > Apruebo para no bloquear el resto de los flujos, pero insisto en que no me queda claro que este endpoint deba estar aca. Me la sensacion que deberia estar en el bot. Sino esto se va a convertir en una especie de bolsa de gatos jajajaj
> 
> A cuál endpoint te referís en específico?

Todos los que se agregan aca :)

2022-09-06 23:21 UTC, merged